AWS_SEARCH_API: ${AWS_SEARCH_API}
AWS_SONG_INFO_API: ${AWS_SONG_INFO_API}
AWS_PROFILE_API: ${AWS_PROFILE_API}

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            clientName: Lyrical-Spring-Boot-Client
            scope: openid, email
            redirectUriTemplate: http://localhost:8080/login/oauth2/code/cognito
        provider:
          cognito:
            issuerUri: ${COGNITO_ISSUER_URI}
            userNameAttribute: username