AWS_SEARCH_API: https://w0nr4pu14l.execute-api.us-east-1.amazonaws.com/dev/search-service?query=
AWS_SONG_INFO_API: https://w0nr4pu14l.execute-api.us-east-1.amazonaws.com/dev/songinfo-service?songID=

spring:
    security:
        oauth2:
            client:
                registration:
                    cognito:
                        client-id: 1e5fhl9vl8ofpb3dntufc7h47s
                        client-secret: 1tda509a099kcqsvquta5ncal6u6i5d61suuqeapvd2a5e725lkt
                        clientName: Lyrical-Spring-Boot-Client
                        scope: openid, email
                        redirectUriTemplate: http://localhost:8080/login/oauth2/code/cognito
                provider:
                    cognito:
                        issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_MP1ezBOmJ
                        userNameAttribute: username